version: '3.4'

services:
  app:
    build: .
    volumes:
      - ./app:/home/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/default
    command: prisma generate --watch

  db:
    image: postgres:13.7-alpine
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
